### ISSUE TITLE
Navigating to `/packages` through the in-page link does not update the navbar menu selection 

### ISSUE THREAD

**Issue by gevou** [usefulio/useful.io#12]
This is a generic bug of the navbar menu. It only updates current selection if you navigate through the navbar.

**Comment by ianserlin** [comment]
True, this is b/c the navbar is not a navbar, it's a materialize tabbar, but I like the animation... so the fix is to see if the animation can be separated... or alternatively, to add an aftertrigger in flowrouter to set the appropriate classes on the nav-tab-bar.

**Comment by ianserlin** [comment]
This is fixed now using a custom version of materialize's tabbar.js doesn't try to show/hide content and a flow router before-hook. I thought it might trigger a double route change, but luckily it does not, I think because the browser knows it's already on the right page.
